let allBees = [
{
  name: "Anthophora abroniae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora abrupta", 
  desc: "Anthophora abrupta is a species of anthophorine be… the family Apidae. It is found in North America.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora affabilis", 
  esc: "unlisted", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora bomboides", 
  desc: "Anthophora bomboides, the bumble-bee-mimic anthoph… the family Apidae. It is found in North America.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora californica", 
  desc: "Anthophora californica, the California anthophora,…It is found in Central America and North America.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora centriformis", 
  desc: "Anthophora centriformis is a species of anthophori…It is found in Central America and North America.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora cockerelli", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora columbariae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora coptognatha", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora crotchii", 
  desc: "Anthophora crotchii, or Crotch's anthophora, is a … the family Apidae. It is found in North America.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora dammersi", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora edwardsii", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora erythrothorax", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora estebana", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora exigua", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora flavocincta", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora flexipes", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"},
{
  name: "Anthophora forbesi", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"},
{
  name: "Anthophora fulvicauda", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"},
{
  name: "Anthophora hololeuca", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"},
{
  name: "Anthophora linsleyi", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora maculifrons", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora mortuaria", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora neglecta", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora nigritula", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", 
  emoji: "🐝"
},
{
  name: "Anthophora pachyodonta", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
  commonName: "Bee", 
  location: "Americas", emoji: "🐝"
},
{
  name: "Anthophora pacifica", 
  desc: "Anthophora pacifica is a species of anthophorine b… the family Apidae. It is found in North America.", 
  commonName: "Bee", 
  location: "Americas", emoji: "🐝"
},
{name: "Anthophora peritomae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora petrophila", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora phaceliae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora phenax", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora platti", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora porterae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora rhodothorax", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora salazariae", 
  desc: "Anthophora salazariae är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora signata", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora terminalis", 
  desc: "Anthophora terminalis is a species of anthophorine… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora urbana", 
  desc: "Anthophora urbana is a species of anthophorine bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora ursina", 
  desc: "Anthophora ursina is a species of anthophorine bee… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophora vannigera", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula albata", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula albicans", 
  desc: "Anthophorula albicans is a species of hymenopteran…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula albovestita", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula cerei", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula chionura", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula cockerelli", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula completa", 
  desc: "Anthophorula completa is a species of hymenopteran…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula deserticola", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula eriogoni", 
  desc: "Anthophorula eriogoni är en biart som först beskre…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula euphorbiae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula minima", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula nitens", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula palmarum", 
  desc: "Anthophorula palmarum is a species of hymenopteran…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula sidae", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula torticornis", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula varleyi", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Anthophorula yoloensis", 
  desc: "The bee genus Anthophora is one of the largest in …solitary, though many nest in large aggregations.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Apis mellifera", 
  desc: "The western honey bee or European honey bee is the… the species' production of honey for the winter.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus affinis", 
  desc: "Bombus affinis, commonly known as the rusty patche…uebec, south to Georgia, and west to the Dakotas.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus appositus", 
  desc: "Bombus appositus is a species of bumblebee known c…ing western Canada and the western United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus ashtoni", 
  desc: "Bombus ashtoni is a species of cuckoo bumblebee. T…s into providing resources such as food for them.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus auricomus", 
  desc: "Bombus auricomus is a species of bumblebee known b…n United States, as far west as the Great Plains.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus bifarius", 
  desc: "Bombus bifarius, the two-form bumblebee, is a comm…nearcticus polymorphisms, present in the species.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus bimaculatus", 
  desc: "The two-spotted bumble bee is a species of social …s bimaculatus, Bremus being a synonym for Bombus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus borealis", 
  desc: "Bombus borealis is a species of bumblebee known co…he northern and eastern contiguous United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus californicus", 
  desc: "Bombus californicus, the California bumble bee, is…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus caliginosus", 
  desc: "Bombus caliginosus, the obscure bumblebee, is a sp…ornia, as far south as the San Jacinto Mountains.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus centralis", 
  desc: "Bombus centralis, the central bumblebee, is a spec…in parts of Canada and the western United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus citrinus", 
  desc: "Bombus citrinus is a species of bumblebee known co…bumblebee. It is native to eastern North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus crotchii", 
  desc: "Bombus crotchii is a species of bumblebee known by…in Mexico and has also been reported from Nevada.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus fernaldae", 
  desc: "Bombus fernaldae, the Fernald's cuckoo bumblebee, …inate Potentilla, Rubus, clovers, and goldenrods.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus fervidus", 
  desc: "Bombus fervidus, the golden northern bumble bee or… Texas, Alaska, and the northern parts of Canada.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus flavifrons", 
  desc: "Bombus flavifrons, the yellow-fronted bumble bee o…Alaska, and the western contiguous United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus franklini", 
  desc: "Franklin's bumblebee is known to be one of the mos…een the Coast and Sierra-Cascade mountain ranges.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus griseocollis", 
  desc: "Bombus griseocollis is a species of bumblebee know…st regions of several of the provinces of Canada.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus huntii", 
  desc: "Bombus huntii is a species of bumblebee. It is nat…mmonly as the Hunt bumblebee or Hunt's bumblebee.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus impatiens", 
  desc: "Bombus impatiens, the common eastern bumble bee, i…s, southern Canada, and the eastern Great Plains.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus insularis", 
  desc: "Bombus insularis is a species of bumblebee in the … commonly as the indiscriminate cuckoo bumblebee.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus melanopygus", 
  desc: "Bombus melanopygus, the black-tailed bumble bee, b…Columbia to California, and as far east as Idaho.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus mixtus", 
  desc: "Bombus mixtus is a species of bumblebee. It is nat…ee, orange-belted bumblebee, and mixed bumblebee.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus morrisoni", 
  desc: "Bombus morrisoni is a species of bumblebee. It is …. It is known commonly as the Morrison bumblebee.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus nevadensis", 
  desc: "Bombus nevadensis, the Nevada bumblebee, is a spec…isconsin, and in Arizona, New Mexico, and Mexico.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus occidentalis", 
  desc: "Bombus occidentalis, the western bumblebee, is one… have confirmed its status as a separate species.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus pensylvanicus", 
  desc: "Bombus pensylvanicus, the American bumblebee, is a…of the Eastern United States, and much of Mexico.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus perplexus", 
  desc: "Bombus perplexus is a species of bumblebee known b…across Canada and into the eastern United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus rufocinctus", 
  desc: "Bombus rufocinctus is a species of bumblebee known…rtheastern United States. It may occur in Mexico.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus sandersoni", 
  desc: "Bombus sandersoni is a species of bumblebee known …s across Canada and in the eastern United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus sitkensis", 
  desc: "Bombus sitkensis, the Sitka bumblebee, is a specie… western North America from Alaska to California.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus sonorus", 
  desc: "Bombus sonorus, the sonoran bumble bee, is a speci…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus suckleyi", 
  desc: "Bombus suckleyi is a species of bumblebee known co…and central Canada and the western United States.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus sylvicola", 
  desc: "Bombus sylvicola is a species of bumblebee native …on. It is known commonly as the forest bumblebee.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus ternarius", 
  desc: "Bombus ternarius, commonly known as the orange-bel…e northeastern United States and parts of Canada.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus terricola", 
  desc: "Bombus terricola, the yellow-banded bumblebee, is …ulate its temperature to fly during cold weather.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus vagans", 
  desc: "The half-black bumblebee is a small bumblebee with…rom Ontario and Nova Scotia southward to Georgia.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus vandykei", 
  desc: "Bombus vandykei, the Van Dyke's bumble bee, is a s… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Bombus vosnesenskii", 
  desc: "Bombus vosnesenskii, the yellow-faced bumblebee, i…an be found in both urban and agricultural areas.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Brachynomada annectens", 
  desc: "Brachynomada annectens is a species of cuckoo bee …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Brachynomada melanantha", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Cemolobus ipomoeae", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Centris californica", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Centris rhodomelas", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina acantha", 
  desc: "Ceratina acantha, the prickly ceratina, is a speci…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina apacheorum", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina arizonensis", 
  desc: "Ceratina arizonensis, the Arizona ceratina, is a s…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina calcarata", 
  desc: "Ceratina calcarata, the spurred ceratina, is a spe… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina dallatorreana", 
  desc: "Ceratina dallatorreana, or Dalla Torre's ceratina,…frica, Europe & Northern Asia, and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina dupla", 
  desc: "Ceratina dupla, the doubled ceratina, is a species…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina hurdi", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina micheneri", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina nanula", 
  desc: "Ceratina nanula, the dwarf ceratina, is a species …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina neomexicana", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina pacifica", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina punctigena", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina sequoiae", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina strenua", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina tejonensis", 
  desc: "Ceratina tejonensis är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Ceratina timberlakei", 
  desc: "The cosmopolitan bee genus Ceratina, often referre…sely related to the more familiar carpenter bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia angusticeps", 
  desc: "Diadasia is a genus of bees in family Apidae. Spec… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia australis", 
  desc: "Diadasia australis is a species of chimney bee in …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia bituberculata", 
  desc: "Diadasia bituberculata is a species of chimney bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia consociata", 
  desc: " Diadasia is a genus of bees in family Apidae. Spe… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia diminuta", 
  desc: "Diadasia diminuta, the globe mallow bee, is a spec…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia enavata", 
  desc: "Diadasia enavata, the sunflower chimney bee, is a …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia laticauda", 
  desc: "Diadasia is a genus of bees in family Apidae. Spec… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia lutzi", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia martialis", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia nigrifrons", 
  desc: "Diadasia nigrifrons är en biart som först beskrevs…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia nitidifrons", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia ochracea", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia opuntiae", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia palmarum", 
  desc: "Diadasia palmarum is een vliesvleugelig insect uit…erst geldig gepubliceerd in 1940 door Timberlake.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia rinconis", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia sphaeralcearum", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia tuberculifrons", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Diadasia vallicola", 
  desc: ". Diadasia is a genus of bees in family Apidae. Sp… likely ancestral host plant for the whole genus.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus americanus", 
  desc: "Epeolus is a genus of cuckoo bees of the tribe Epe…. They are often known as variegated cuckoo-bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus asperatus", 
  desc: "Epeolus is a genus of cuckoo bees of the tribe Epe…. They are often known as variegated cuckoo-bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus bifasciatus", 
  desc: "Epeolus bifasciatus, the cuckoo bee, is a species …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus compactus", 
  desc: "Epeolus compactus is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus interruptus", 
  desc: "Epeolus is a genus of cuckoo bees of the tribe Epe…. They are often known as variegated cuckoo-bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus mesillae", 
  desc: "Epeolus mesillae is a species of cuckoo bee in the…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus minimus", 
  desc: "Epeolus minimus is a species of cuckoo bee in the …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus pusillus", 
  desc: "Epeolus pusillus, the cuckoo bee, is a species of …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Epeolus scutellaris", 
  desc: "Epeolus scutellaris is a species of cuckoo bee in …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera acerba", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera actuosa", 
  desc: "Eucera actuosa is a species of long-horned bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera albescens", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera amsinckiae", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera angustifrons", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera californica", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera cordleyi", 
  desc: "Eucera cordleyi is a species of long-horned bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera delphinii", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera dorsata", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera edwardsii", 
  desc: "Eucera edwardsii is a species of long-horned bee i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera frater", 
  desc: "Eucera frater is a species of long-horned bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera fulvitarsis", 
  desc: "Eucera fulvitarsis is a species of long-horned bee… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera hamata", 
  desc: "Eucera hamata is a species of long-horned bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera hurdi", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera lunata", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera mohavensis", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera monozona", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera primiveris", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera quadricincta", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera stretchii", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera territella", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera tricinctella", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera virgata", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Eucera zonata", 
  desc: "Eucera is a genus of bees in the family Apidae, su…pinae, and tribe Eucerini - the long-horned bees.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Exomalopsis solidaginis", 
  desc: "Exomalopsis is a genus of bees in the family Apida…pecially in the Neotropical and Nearctic regions.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda cineraria", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda dammersi", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda depressa", 
  desc: "Habropoda depressa is a species of anthophorine be… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda excellens", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda miserabilis", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda morrisoni", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda murihirta", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda salviae", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda semifulva", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Habropoda tristissima", 
  desc: "Habropoda tristissima is a species of anthophorine…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Holcopasites arizonicus", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Holcopasites bohartorum", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Holcopasites calliopsidis", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Holcopasites insoletus", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Holcopasites ruthae", 
  desc: "Habropoda is a genus of anthophorine bees in the f…e are at least 50 described species in Habropoda.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melecta edwardsii", 
  desc: "Melecta edwardsii, or Edward's melectum, is a spec…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melecta pacifica", 
  desc: "Melecta pacifica is a species of hymenopteran in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melecta separata", 
  desc: "Melecta pacifica is a species of hymenopteran in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melecta thoracica", 
  desc: "Melecta thoracica är en biart som beskrevs av Cres…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes agilis", 
  desc: "Melissodes agilis, the agile long-horned bee, is a…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes bimatris", 
  desc: "Melecta bimartris is a species of hymenopteran in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes brevipyga", 
  desc: "Melecta brevipyga is a species of hymenopteran in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes clarkiae", 
  desc: "Melecta clarkiae is a species of hymenopteran in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes coloradensis", 
  desc: "Melecta coloradensis is a species of hymenopteran … the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes communis", 
  desc: "Melissodes communis, the common long-horned bee, i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes glenwoodensis", 
  desc: "Melissodes communis, the common long-horned bee, i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes grindeliae", 
  desc: "Melissodes communis, the common long-horned bee, i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes hurdi", 
  desc: "Melissodes communis, the common long-horned bee, i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes hymenoxidis", 
  desc: "Melissodes communis, the common long-horned bee, i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes limbus", 
  desc: "Melissodes limbus är en biart som beskrevs av Labe…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes menuachus", 
  desc: "Melissodes menuachus är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes micheneri", 
  desc: "Melissodes micheneri är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes monoensis", 
  desc: "Melissodes monoensis är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes moorei", 
  desc: "Melissodes moorei är en biart som beskrevs av Cock…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes nigracauda", 
  desc: "Melissodes nigracauda är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes ochraea", 
  desc: "Melissodes ochraea är en biart som beskrevs av Lab…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes paroselae", 
  desc: "Melissodes paroselae, the parosela long-horned bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes rivalis", 
  desc: "Melissodes rivalis is a species of long-horned bee… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes robustior", 
  desc: "Melissodes robustior, the robust long-horned bee, … the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes saponellus", 
  desc: "Melissodes saponellus is a species of long-horned … the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes stearnsi", 
  desc: "Melissodes stearnsi is a species of long-horned be… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes subagilis", 
  desc: "Melissodes subagilis är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes thelypodii", 
  desc: "Melissodes thelypodii är en biart som beskrevs av …r i släktet Melissodes och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes tribas", 
  desc: "Melissodes tribas is a species of long-horned bee …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes tristis", 
  desc: "Melissodes tristis is a species of long-horned bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes utahensis", 
  desc: "Melissodes utahensis är en biart som beskrevs av L…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes verbesinarum", 
  desc: "Melissodes verbesinarum är en biart som beskrevs a…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Melissodes vernalis", 
  desc: "Melissodes vernalis är en biart som beskrevs av Co…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra alba", 
  desc: "Neolarra batrae är en biart som beskrevs av Shanks…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra batrae", 
  desc: "Neolarra batrae är en biart som beskrevs av Shanks…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra californica", 
  desc: "Neolarra californica is a species of cuckoo bee in…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra clavigera", 
  desc: "Neolarra clavigera is a species of cuckoo bee in t…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra hurdi", 
  desc: "Neolarra hurdi is a species of cuckoo bee in the f…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra linsleyi", 
  desc: "Neolarra linsleyi is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra orbiculata", 
  desc: "Neolarra orbiculata is a species of cuckoo bee in …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra penicula", 
  desc: "Neolarra penicula is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra pruinosa", 
  desc: "Neolarra pruinosa is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra vandykei", 
  desc: "Neolarra vandykei is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neolarra vigilans", 
  desc: "Neolarra vigilans is a species of cuckoo bee in th…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neopasites cressoni", 
  desc: "Neopasites cressoni är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neopasites fulviventris", 
  desc: "Neopasites fulviventris is a species of cuckoo bee… the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neopasites sierrae", 
  desc: "Neopasites is a genus of cuckoo bees in the family…here are about 5 described species in Neopasites.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Neopasites timberlakei", 
  desc: "Neopasites is a genus of cuckoo bees in the family…here are about 5 described species in Neopasites.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada accepta", 
  desc: "Nomada accepta är en biart som beskrevs av Cockere…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada angelarum", 
  desc: "Nomada angelarum är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada articulata", 
  desc: "Nomada articulata is a species of nomad bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada ashmeadi", 
  desc: "Nomada ashmeadi är en biart som beskrevs av Cocker…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada atrofrontata", 
  desc: "Nomada atrofrontata är en biart som beskrevs av Co…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada banksi", 
  desc: "Nomada banksi är en biart som beskrevs av Cockerel…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada bella", 
  desc: "Nomada bella är en biart som beskrevs av Cockerell…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada bethunei", 
  desc: "Nomada bethunei, the cuckoo bee, is a species of nomad bee in the family Apidae.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada bifurcata", 
  desc: "Nomada bifurcata är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada californiae", 
  desc: "Nomada californiae är en biart som beskrevs av Mit…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada citrina", 
  desc: "Nomada citrina är en biart som beskrevs av Mitchel…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada composita", 
  desc: "Nomada composita är en biart som beskrevs av Mitch…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada coquilletti", 
  desc: "Nomada coquilletti är en biart som beskrevs av Rob…ngår i släktet gökbin, och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada cressonii", 
  desc: "Nomada cressonii är en biart som beskrevs av Rober…ngår i släktet gökbin, och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada crotchii", 
  desc: "Nomada crotchii is a species of nomad bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada cuneata", 
  desc: "Nomada cuneata is a species of nomad bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada davidsoni", 
  desc: "Nomada davidsoni is a species of nomad bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada debilis", 
  desc: "Nomada debilis är en biart som beskrevs av Timberl…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada denticulata", 
  desc: "Nomada denticulata är en biart som beskrevs av Cre…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada depressa", 
  desc: "Nomada depressa är en biart som beskrevs av Cresso…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada detrita", 
  desc: "Nomada detrita är en biart som beskrevs av Mitchel…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada dreisbachi", 
  desc: "Nomada dreisbachi är en biart som beskrevs av Mitc…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada edwardsii", 
  desc: "Nomada edwardsii, the Edwards' nomad bee, is a spe…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada electa", 
  desc: "Nomada electa is a species of nomad bee in the family Apidae.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada elegantula", 
  desc: "Nomada elegantula is a species of nomad bee in the family Apidae.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada erythraea", 
  desc: "Nomada erythraea är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada erythrospila", 
  desc: "Nomada erythrospila är en biart som beskrevs av Co…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada florilega", 
  desc: "Nomada florilega är en biart som beskrevs av Lovel…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada formula", 
  desc: "Nomada formula är en biart som beskrevs av Henry L…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada fragilis", 
  desc: "Nomada fragilis är en biart som beskrevs av Cocker…ngår i släktet gökbin, och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada grayi", 
  desc: "Nomada grayi är en biart som beskrevs av Cockerell…ngår i släktet gökbin, och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada hemphilli", 
  desc: "Nomada hemphilli is a species of nomad bee in the …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada hesperia", 
  desc: "Nomada hesperia är en biart som beskrevs av Dalla …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada hurdi", 
  desc: "Nomada hurdi är en biart som beskrevs av Dalla Tor…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada imbricata", 
  desc: "Nomada imbricata är en biart som beskrevs av Dalla…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada integerrima", 
  desc: "Nomada integerrima är en biart som beskrevs av Dal…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada interruptella", 
  desc: "Nomada interruptella är en biart som beskrevs av F…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada latifrons", 
  desc: "Nomada latifrons är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada lehighensis", 
  desc: "Nomada lehighensis är en biart som beskrevs av Coc…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada lepida", 
  desc: "Nomada lepida är en biart som beskrevs av Cresson …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada linsleyi", 
  desc: "Nomada linsleyi är en biart som beskrevs av Evans …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada luteola", 
  desc: "Nomada luteola is a species of nomad bee in the family Apidae.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada luteoloides", 
  desc: "Nomada luteoloides is a species of nomad bee in the family Apidae.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada maculata", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada marginella", 
  desc: "Nomada marginella är en biart som beskrevs av Cock…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada mckenziei", 
  desc: "Nomada mckenziei är en biart som beskrevs av Timbe…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada mediana", 
  desc: "Nomada mediana är en biart som beskrevs av Swenk 1…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada melanosoma", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada melliventris", 
  desc: "Nomada melliventris är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada mendica", 
  desc: "Nomada melliventris är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada mutans", 
  desc: "Nomada melliventris är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada obliquella", 
  desc: "Nomada melliventris är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada obscurella", 
  desc: "Nomada melliventris är en biart som beskrevs av Cr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada opacella", 
  desc: "Nomada opacella är en biart som beskrevs av Timber…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada opposita", 
  desc: "Nomada opposita är en biart som beskrevs av Cresso…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada orcusella", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada osborni", 
  desc: "Nomada osborni är en biart som beskrevs av Cockere…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada ovata", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada parva", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada pascoensis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada perbella", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada perplexa", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada pygmaea", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada pyrrha", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rhodalis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rhodomelas", 
  desc: "Nomada rhodomelas är en biart som beskrevs av Cock…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rhodosoma", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rhodotricha", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rivalis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada rubrica", 
  desc: "Nomada rubrica är en biart som beskrevs av Léon Ab…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada sanctaecrucis", 
  desc: "Nomada sanctaecrucis är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada sayi", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada schwarzi", 
  desc: "Nomada schwarzi är en biart som beskrevs av Cocker…ngår i släktet gökbin, och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada semisuavis", 
  desc: "Nomada semisuavis är en biart som beskrevs av Cock…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada simplicicoxa", 
  desc: "Nomada sophiarum är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada sophiarum", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada suavis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada subangusta", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada subgracilis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada subvicinalis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada sulphurata", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada timberlakei", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada tintinnabulum", 
  desc: "Nomada tintinnabulum är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada ultimella", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada valida", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada verecunda", 
  desc: "Nomada verecunda is a species in the family Apidae, in the order Hymenoptera.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada vicina", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada vicinalis", 
  desc: "With over 850 species, the genus Nomada is one of …es of bees as hosts, primarily the genus Andrena.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Nomada xanthura", 
  desc: "Nomada xanthura är en biart som beskrevs av Cocker…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites albinota", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites euphorbiae", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites hurdi", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites linsleyi", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites powelli", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Oreopasites vanduzeei", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Paranomada californica", 
  desc: "Peponapis californica is a species of solitary bee…s well as the other squash bee genus, Xenoglossa.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Peponapis pruinosa", 
  desc: "Peponapis pruinosa is a species of solitary bee in…s well as the other squash bee genus, Xenoglossa.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Peponapis timberlakei", 
  desc: "Peponapis timberlakei är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra duplocincta", 
  desc: "Svastra duplocincta is a species of long-horned be…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra helianthelli", 
  desc: "Svastra duplocincta is a species of long-horned be…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"}
{name: "Svastra machaerantherae", 
  desc: "Svastra machaerantherae is a species of long-horne…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra nevadensis", 
  desc: "Svastra nevadensis, the sunflower bee, is a specie…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra obliqua", 
  desc: "Svastra obliqua, the sunflower bee, is a species o…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra pallidior", 
  desc: "Svastra pallidior is a species of long-horned bee …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra sabinensis", 
  desc: "Svastra sabinensis is a species of long-horned bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Svastra texana", 
  desc: "Svastra texana is a species of long-horned bee in …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Tetraloniella davidsoni", 
  desc: "Tetraloniella davidsoni är en biart som beskrevs a…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Tetraloniella distata", 
  desc: "Tetraloniella distata är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Tetraloniella eriocarpi", 
  desc: "Tetraloniella eriocarpi is a species of long-horne…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Tetraloniella pomonae", 
  desc: "Tetraloniella pomonae is a species of long-horned …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Tetraloniella vandykei", 
  desc: "Tetraloniella vandykei är en biart som beskrevs av…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus ancoratus", 
  desc: "Triepeolus ancoratus är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus antiochensis", 
  desc: "Triepeolus antiochensis är en biart som beskrevs a…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus argentimus", 
  desc: "Triepeolus argentimus är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus argyreus", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus blaisdelli", 
  desc: "Triepeolus blaisdelli är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus brunnescens", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus californicus", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus callopus", 
  desc: "Triepeolus callopus är en biart som beskrevs av Co…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus concavus", 
  desc: "Triepeolus concavus is a species of cuckoo bee in …It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus cressonii", 
  desc: "Triepeolus cressonii är en biart som först beskrev…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus diffusus", 
  desc: "Triepeolus diffusus är en biart som beskrevs av Mo…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus diversipes", 
  desc: "Triepeolus diversipes är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus donatus", 
  desc: "Triepeolus donatus is a species of cuckoo bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus edwardi", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus fraserae", 
  desc: "Triepeolus fraserae är en biart som beskrevs av Co…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus helianthi", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus inyoensis", 
  desc: "Triepeolus inyoensis är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus joliae", 
  desc: "Triepeolus joliae är en biart som beskrevs av Moll…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus lunatus", 
  desc: "Triepeolus lunatus, the cuckoo bee, is a species o…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus melanarius", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus michiganensis", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus micropygius", 
  desc: "Triepeolus micropygius är en biart som beskrevs av…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus mojavensis", 
  desc: "Triepeolus mojavensis är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus norae", 
  desc: "Triepeolus norae är en biart som beskrevs av Cocke…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus pectoralis", 
  desc: "Triepeolus pectoralis is a species of cuckoo bee in the family Apidae. It is found in North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus penicilliferus", 
  desc: "Triepeolus penicilliferus är en biart som först be…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus permixtus", 
  desc: "Triepeolus permixtus är en biart som först beskrev…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus perpictus", 
  desc: "Triepeolus perpictus är en biart som beskrevs av M…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus pomonalis", 
  desc: "Triepeolus pomonalis är en biart som beskrevs av C…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus punctoclypeus", 
  desc: "Triepeolus punctoclypeus är en biart som beskrevs …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus quadratus", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus remigatus", 
  desc: "Triepeolus remigatus, the cuckoo bee, is a species…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus robustus", 
  desc: "Triepeolus robustus är en biart som först beskrevs…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus sarothrinus", 
  desc: "Triepeolus sarothrinus är en biart som först beskr…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus saturninus", 
  desc: "Triepeolus saturninus är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus schwarzi", 
  desc: "Triepeolus schwarzi är en biart som beskrevs av Co…r i släktet Triepeolus och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus simulatus", 
  desc: "Triepeolus simulatus är en biart som beskrevs av M…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus subalpinus", 
  desc: "Triepeolus subalpinus är en biart som beskrevs av …nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus subnitens", 
  desc: "unlisted", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus timberlakei", 
  desc: "Triepeolus timberlakei är en biart som beskrevs av…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus utahensis", 
  desc: "Triepeolus utahensis är en biart som först beskrev…nga underarter finns listade i Catalogue of Life.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Triepeolus verbesinae", 
  desc: "Triepeolus verbesinae is a species of cuckoo bee i…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xenoglossa angustior", 
  desc: "Xenoglossa angustior is a species of long-horned b…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xenoglossa patricia", 
  desc: "Xenoglossa patricia is a species of long-horned be…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xenoglossa strenua", 
  desc: "Xenoglossa strenua is a species of long-horned bee…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xeromelecta californica", 
  desc: "Xeromelecta californica, the California xeromelect…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xeromelecta larreae", 
  desc: "Xeromelecta larreae, the larrea xeromelectum, is a…It is found in Central America and North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xylocopa californica", 
  desc: "The California carpenter bee, Xylocopa californica…menoptera. It is native to western North America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xylocopa micans", 
  desc: "Xylocopa micans, also known as the southern carpen… Mexico and Guatemala. Like all Xylocopa bees, X.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xylocopa tabaniformis", 
  desc: "Xylocopa tabaniformis, the horsefly-like carpenter…entral America, North America, and South America.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xylocopa varipuncta", 
  desc: "Xylocopa varipuncta, the valley carpenter bee, is …n California, growing to around 1 inch in length.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Xylocopa virginica", 
  desc: "Xylocopa virginica, more commonly known as the eas… various types of wood and eat pollen and nectar.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"},
{name: "Zacosmia maculata", 
  desc: "Zacosmia maculata är en biart som först beskrevs a…går i släktet Zacosmia och familjen långtungebin.", 
commonName: "Bee", 
  location: "Americas", emoji: "🐝"}
];